INSERT INTO research_group ("name", abstract, maintainer, created_on, "language", image) VALUES ('LiSS', 'O Laboratório de Investigação Sistemas Socioambientais (LiSS) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. Ele tem como objeto estudar a influencia das atividade antrópicas nas mudanças de uso e cobertura da Terra. A principal área de estudo do LiSS é a Amazônia Legal, porém pesquisas também vem sendo feitas na região do Vale Paraibano (SP) e no bioma do Pantanal.', 'username', '2019-09-04T14:48:54+00:00', 'Português','assets/images/liss.png');

INSERT INTO research_group ("name", abstract, maintainer, created_on, "language", image) VALUES ('LabISA', 'O Laboratório de Instrumentação de Sistemas Aquáticos (LabISA) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. O laboratório foi motivado pelo aumento no número de estudos voltados à aplicações de sensoriamento remoto para estimativa de propriedades físicas, biológicas e químicas de águas continentais. A principal atividade do laboratório é coleta de dados sobre propriedades óticas e limnológicas de águas interiores e costeiras.', 'username', '2019-09-04T14:48:54+00:00', 'Português', 'assets/images/labisa.png');

INSERT INTO research_group ("name", abstract, maintainer, created_on, "language", image) VALUES ('LAF', 'O Laboratório de Investigação Sistemas Socioambientais (LiSS) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. Ele tem como objeto estudar a influencia das atividade antrópicas nas mudanças de uso e cobertura da Terra. A principal área de estudo do LiSS é a Amazônia Legal, porém pesquisas também vem sendo feitas na região do Vale Paraibano (SP) e no bioma do Pantanal.', 'username', '2019-09-04T14:48:54+00:00', 'Português', 'assets/images/laf.png');

INSERT INTO research_group ("name", abstract, maintainer, created_on, "language", image) VALUES ('TREES', 'O Laboratório de Instrumentação de Sistemas Aquáticos (LabISA) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. O laboratório foi motivado pelo aumento no número de estudos voltados à aplicações de sensoriamento remoto para estimativa de propriedades físicas, biológicas e químicas de águas continentais. A principal atividade do laboratório é coleta de dados sobre propriedades óticas e limnológicas de águas interiores e costeiras.', 'username', '2019-09-04T14:48:54+00:00', 'Português', 'assets/images/trees.png');

INSERT INTO research_group ("name", abstract, maintainer, created_on, "language", image) VALUES ('LOA', 'O Laboratório de Instrumentação de Sistemas Aquáticos (LabISA) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. O laboratório foi motivado pelo aumento no número de estudos voltados à aplicações de sensoriamento remoto para estimativa de propriedades físicas, biológicas e químicas de águas continentais. A principal atividade do laboratório é coleta de dados sobre propriedades óticas e limnológicas de águas interiores e costeiras.', 'username', '2019-09-04T14:48:54+00:00', 'Português', 'assets/images/loa.png');

INSERT INTO research_group ("name", abstract, maintainer, created_on, "language", image) VALUES ('LiSS', 'O Laboratório de Investigação Sistemas Socioambientais (LiSS) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. Ele tem como objeto estudar a influencia das atividade antrópicas nas mudanças de uso e cobertura da Terra. A principal área de estudo do LiSS é a Amazônia Legal, porém pesquisas também vem sendo feitas na região do Vale Paraibano (SP) e no bioma do Pantanal.', 'username', '2019-09-04T14:48:54+00:00', 'Português','assets/images/liss.png');

INSERT INTO research_data_repositories ("name", abstract, maintainer, created_on) VALUES ('LiSS Repository', 'O Laboratório de Investigação Sistemas Socioambientais (LiSS) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. Ele tem como objeto estudar a influencia das atividade antrópicas nas mudanças de uso e cobertura da Terra. A principal área de estudo do LiSS é a Amazônia Legal, porém pesquisas também vem sendo feitas na região do Vale Paraibano (SP) e no bioma do Pantanal.', 'username', '2019-09-04T14:48:54+00:00');

INSERT INTO research_data_repositories ("name", abstract, maintainer, created_on) VALUES ('LabISA Repository', 'O Laboratório de Instrumentação de Sistemas Aquáticos (LabISA) é um dos laboratórios que compõe a Coordenação-Geral de Observação da Terra OBT-INPE. O laboratório foi motivado pelo aumento no número de estudos voltados à aplicações de sensoriamento remoto para estimativa de propriedades físicas, biológicas e químicas de águas continentais. A principal atividade do laboratório é coleta de dados sobre propriedades óticas e limnológicas de águas interiores e costeiras.', 'username', '2019-09-04T14:48:54+00:00');

INSERT INTO ports (port) VALUES ('5432');
INSERT INTO ports (port) VALUES ('5555');
INSERT INTO ports (port) VALUES ('5050');
INSERT INTO ports (port) VALUES ('5000');
